# Site settings
name: Rielle Quiambao
title: Rielle Quiambao
description: Data-focused software engineer and aspiring data scientist
url: https://baorie.github.io
baseurl: ""
email: rielle.quiambao@gmail.com
cover: https://baorie.github.io/img/og.png
logo: https://baorie.github.io/img/emojis/technologist.png
resume: https://baorie.github.io/resume.pdf
social:
  - title: email
    url: mailto:rielle.quiambao@gmail.com
  - title: github
    url: https://github.com/baorie
  - title: linkedin
    url: https://www.linkedin.com/in/riellemq/
  - title: medium
    url: https://medium.com/@rielle.quiambao

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
